name: JMD
favicon: null
layout_spectrum: 0.90794
typography_spectrum: 0.53369
title: 'Joshua Michael Designs, LLC'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#34dfcd'
    - '#a7f9f2'
    - '#115623'
    - '#000100'
    - '#207c35'
  brandStrength: 0
  lightness: 0.8125
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
