name: JMD
favicon: null
layout_spectrum: 0.90794
typography_spectrum: 0.53369
title: 'Joshua Michael Designs, LLC'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#69645e'
    - '#81a0a5'
    - '#3e220a'
    - '#cba075'
  brandStrength: 0.375
  lightness: 0.8125
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
